# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.0.2.dev6+gbe87243.d20230714'
__version_tuple__ = version_tuple = (1, 0, 2, 'dev6', 'gbe87243.d20230714')
